### PR TITLE
Add vendor libs from Icinga Web and support PHP 8.2

### PR DESCRIPTION
**Pull request by raviks789**
- Vendor libraries from icingaweb2 moved to `composer.json`
- Migrated from Zend1 fork to [zf1-future](https://github.com/Shardj/zf1-future)@[1.22.0](https://github.com/Shardj/zf1-future/releases/tag/release-1.22.0)
- Versions are changed to the highest minimum stability versions which also enables PHP 8.2 support
- PHP version is now required to be >= 7.2.9 (As `wikimedia/less` requires PHP>=7.2.9)

Blocked by #12 

closes #9 
closes #10

### CODE REVIEW

**Comment by lippserd** [comment]
> * PHP version is now required to be >= 7.3 (As this is the minimum version being supported right now by debian/rpm-based distribution and `wikimedia/less` requires PHP>=7.3)

I'm ok with PHP 7.3 but the actual requirement from [wikimedia/less is 7.2.9](https://github.com/wikimedia/less.php/blob/v3.2.1/composer.json#L44).

**Review by lippserd — CHANGES_REQUESTED** [review]
I don't understand this commit description:

> `wikimedia/less` requires `php >= 7.2.9`. Hence, the minimum php version requirement to `7.3` (this
is the minimum version being supported right now by debian/rpm-based distribution) has also been updated.

If 7.2.9 is the minimum requirement, why require PHP 7.3? Again, I'm ok with that but that description doesn't fit.

**Comment by raviks789** [comment]
> I don't understand this commit description:
> 
> > `wikimedia/less` requires `php >= 7.2.9`. Hence, the minimum php version requirement to `7.3` (this
> > is the minimum version being supported right now by debian/rpm-based distribution) has also been updated.
> 
> If 7.2.9 is the minimum requirement, why require PHP 7.3? Again, I'm ok with that but that description doesn't fit.

PHP 7.2 has reached EOL in all distributions, hence instead of just updating PHP version to 7.2.9, I updated it to 7.3 (which still receives Active support till `30.06.2024`)

**Review by lippserd — CHANGES_REQUESTED** [review]
Apart from our discussion, to be honest, our libraries should only require minimum versions and that is PHP 7.2.9.

**Comment by raviks789** [comment]
> Apart from our discussion, to be honest, our libraries should only require minimum versions and that is PHP 7.2.9.

I have changed the version back to PHP 7.3. This is the version used by Centos 7 when the packages are built and all other OS uses higher PHP versions.

Also, some vendor libraries like `guzzlehttp/psr7`  has added PHP 8.2 after removing PHP 7.2 support.

**Comment by lippserd** [comment]
> 

Current PR shows 7.2.9. Is this comment outdated?

**Comment by raviks789** [comment]
> > > Apart from our discussion, to be honest, our libraries should only require minimum versions and that is PHP 7.2.9.
> > 
> > 
> > I have changed the version back to PHP 7.3. This is the version used by Centos 7 when the packages are built and all other OS uses higher PHP versions.
> > Also, some vendor libraries like `guzzlehttp/psr7` has added PHP 8.2 after removing PHP 7.2 support.
> 
> Current PR diff shows `7.2.9`. Is this comment outdated?

That comment could be considered outdated.

**Review by lippserd — CHANGES_REQUESTED** [review]
```
diff --git a/composer.json b/composer.json
index 6155732..713c810 100644
--- a/composer.json
+++ b/composer.json
@@ -21,7 +21,7 @@
         "clue/http-proxy-react": "^1.8",
         "clue/mq-react": "^1.5",
         "clue/redis-react": "^2.6",
-        "clue/soap-react": "^1",
+        "clue/soap-react": "^2.0",
         "clue/socket-raw": "^1.6",
         "clue/socks-react": "^1.4",
         "clue/stdio-react": "^2.6",
@@ -33,9 +33,9 @@
         "guzzlehttp/guzzle": "^7.7",
         "guzzlehttp/psr7": "^2.5",
         "jfcherng/php-diff": "^6.10",
-        "predis/predis": "^1.1",
+        "predis/predis": "^2.2",
         "psr/http-message": "^1.1",
-        "ramsey/uuid": "^3.9",
+        "ramsey/uuid": "^4.2",
         "react/child-process": "^0.6",
         "react/datagram": "^1.9",
         "react/dns": "^1.11",

**Comment by nilmerg** [comment]
Ah, okay. I've confused `^` with `~`. :bulb:

**Review by lippserd — APPROVED** [review]

**Pull request merged**
